# Generated by Django 2.2.17 on 2021-01-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
