export const DO_LOGIN = "DO_LOGIN";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const DO_LOGIN_SUCCEEDED = "DO_LOGIN_SUCCEEDED";
export const DO_LOGIN_FAILED = "DO_LOGIN_FAILED";
export const DO_LOGOUT = "DO_LOGOUT";

export const DO_FBLOGIN = "DO_FBLOGIN";
export const DO_FBLOGIN_SUCCEEDED = "DO_FBLOGIN_SUCCEEDED";
export const DO_FBLOGIN_FAILED = "DO_FBLOGIN_FAILED";

export const DO_GOOGLELOGIN = "DO_GOOGLELOGIN";
export const DO_GOOGLELOGIN_SUCCEEDED = "DO_GOOGLELOGIN_SUCCEEDED";
export const DO_GOOGLELOGIN_FAILED = "DO_GOOGLELOGIN_FAILED";

export const DO_APPLELOGIN = "DO_APPLELOGIN";
export const DO_APPLELOGIN_SUCCEEDED = "DO_APPLELOGIN_SUCCEEDED";
export const DO_APPLELOGIN_FAILED = "DO_APPLELOGIN_FAILED";

export const DO_REGISTER = "DO_REGISTER";
export const DO_REGISTER_SUCCEEDED = "DO_REGISTER_SUCCEEDED";
export const DO_REGISTER_FAILED = "DO_REGISTER_FAILED";

export const DO_PWDRESET = "DO_PWDRESET";
export const DO_PWDRESET_SUCCEEDED = "DO_PWDRESET_SUCCEEDED";
export const DO_PWDRESET_FAILED = "DO_PWDRESET_FAILED";

export const DO_GET_TERMS = "DO_GETTERMS";
export const DO_GET_TERMS_SUCCEEDED = "DO_GETTERMS_SUCCEEDED";
export const DO_GET_TERMS_FAILED = "DO_GETTERMS_FAILED";

export const DO_ADD_FCM_DEVICE = "DO_ADD_FCM_DEVICE";
