# Generated by Django 2.2.19 on 2021-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='crossed',
            field=models.BooleanField(default=False),
        ),
    ]
