import { StyleSheet } from "react-native";

export const appBackgroundColor = "#F5F5F5";
export const headerBackgroundColor = "#61BAAC";
export const appFontFamily = "Nunito";
export const FONT_FAMILY = "Nunito";
export const COLOR_GRAY_1 = "#4C4C4C";
export const COLOR_GRAY_2 = "#999999";
export const COLOR_GRAY_3 = "#A9A9A9";
export const COLOR_GRAY_4 = "#DDDDDD";
export const COLOR_GRAY_5 = "#E6E6E6";
export const COLOR_RED = "#F04D4D";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: appBackgroundColor,
  },
  safeAreaStyle: {
    flex: 0,
    backgroundColor: appBackgroundColor,
  },
  safeAreaDarkHeaderStyle: {
    flex: 0,
    backgroundColor: headerBackgroundColor,
  },
  safeAreaContentStyle: {
    flex: 1,
    backgroundColor: headerBackgroundColor,
  },
  safeAreaLightFooterStyle: {
    flex: 0,
    backgroundColor: appBackgroundColor,
  },
  content_h1_bold: {
    color: "black",
    fontSize: 18,
    fontFamily: FONT_FAMILY,
    fontWeight: "900",
    lineHeight: 25,
    textAlign: "center",
  },
  content_h1: {
    color: "black",
    fontSize: 19,
    fontFamily: FONT_FAMILY,
    fontFamily: FONT_FAMILY,
    fontWeight: "700",
    lineHeight: 25,
    textAlign: "center",
  },
  content_h2_bold: {
    color: "black",
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    fontWeight: "700",
    lineHeight: 21,
  },
  content_p_bold: {
    color: "black",
    fontSize: 14,
    fontFamily: FONT_FAMILY,
    fontWeight: "700",
    lineHeight: 20,
  },
  content_semi: {
    color: "black",
    fontSize: 14,
    fontFamily: FONT_FAMILY,
    fontWeight: "600",
    lineHeight: 20,
  },
  content_regular: {
    color: "black",
    fontSize: 14,
    fontFamily: FONT_FAMILY,
    lineHeight: 20,
    fontWeight: "400",
    textAlign: "center",
  },
  content_smallprint: {
    color: COLOR_GRAY_3,
    fontSize: 12,
    fontFamily: FONT_FAMILY,
    lineHeight: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  content_listdescription: {
    color: COLOR_GRAY_1,
    fontSize: 14,
    fontFamily: FONT_FAMILY,
    lineHeight: 19,
    fontWeight: "600",
    textAlign: "center",
  },
  buttonPrimary: {
    height: 50,
    color: "white",
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    lineHeight: 20,
    alignItems: "center",
    borderColor: "#61BAAC",
    borderWidth: 1,
    width: "100%",
    borderRadius: 14,
    justifyContent: "center",
    paddingVertical: "3%",
    backgroundColor: "#61BAAC",
    flexDirection: "row",
    marginBottom: 30,
  },

  buttonPrimaryDisabled: {
    height: 50,
    color: "white",
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    lineHeight: 20,
    alignItems: "center",
    borderColor: "#DDDDDD",
    borderWidth: 1,
    width: "100%",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: "3%",
    backgroundColor: "#DDDDDD",
    flexDirection: "row",
  },
  buttonPrimaryDisabledText: {
    color: "#A9A9A9",
    fontSize: 17,
    fontFamily: FONT_FAMILY,
    fontWeight: "600",
    position: "absolute",
  },
  buttonPrimaryText: {
    color: "white",
    fontSize: 17,
    fontFamily: FONT_FAMILY,
    fontWeight: "600",
    position: "absolute",
  },
  buttonSecondary: {
    height: 50,
    color: "black",
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    lineHeight: 20,
    alignItems: "center",
    borderColor: "#61BAAC",
    borderWidth: 1,
    width: "100%",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonSecondaryText: {
    color: headerBackgroundColor,
    fontSize: 17,
    fontFamily: FONT_FAMILY,
    fontWeight: "600",
  },
  filler: {
    flex: 1,
  },
  scrollHolderForHeaderScreen: {
    flex: 1,
    backgroundColor: appBackgroundColor,
    marginTop: 20,
    borderTopStartRadius: 20,
    borderTopEndRadius: 20,
    paddingTop: 20,
  },
  scrollContentContainerOfHeaderScreen: {
    paddingHorizontal: 25,
    flex: 1,
  },
  errorText: {
    fontFamily: FONT_FAMILY,
    fontStyle: "normal",
    fontSize: 12,
    lineHeight: 18,
    alignItems: "center",
    textAlign: "center",
    color: "#F04D4D",
  },
  buttonBookmarkCategorySelected: {
    height: 50,
    color: "black",
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    lineHeight: 20,
    alignItems: "center",
    borderColor: "#61BAAC",
    borderWidth: 1,
    //width:'100%',
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonBookmarkCategorySelectedText: {
    color: headerBackgroundColor,
    fontSize: 17,
    fontFamily: FONT_FAMILY,
    fontWeight: "600",
  },
  buttonBookmarkGroup: {
    height: 35,
    paddingHorizontal: 10,
    marginTop: 10,
    marginRight: 10,
    color: "black",
    fontSize: 16,
    fontFamily: FONT_FAMILY,
    lineHeight: 20,
    alignItems: "center",
    borderColor: COLOR_GRAY_3,
    borderWidth: 1,
    //width:'100%',
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonBookmarkGroupText: {
    color: COLOR_GRAY_3,
    fontSize: 13,
    fontFamily: FONT_FAMILY,
    fontWeight: "700",
  },
  activityIndicatorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    position: "absolute",
    height: "100%",
    width: "100%",
    backgroundColor: "rgba(0,0,0,0.2)",
  },
});
