# Generated by Django 2.2.17 on 2021-01-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20210105_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_bookmark', to='recipe.Recipe'),
        ),
    ]
