# Generated by Django 2.2.19 on 2021-03-05 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_images_recipeimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0005_auto_20210304_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('recipe', 'user')},
        ),
    ]
