# Generated by Django 2.2.23 on 2021-07-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_auto_20210305_1117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
