# Generated by Django 2.2.23 on 2021-07-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0028_reciperatings'),
        ('bookmarks', '0007_auto_20210716_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('recipe', 'group')},
        ),
    ]
