# Generated by Django 2.2.23 on 2021-07-16 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0028_reciperatings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0008_auto_20210716_1518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('recipe', 'user')},
        ),
    ]
