// prettier-ignore
export const ADD_RECIPE_ISLOADING = "ADD_RECIPE_ISLOADING";
export const ADD_RECIPE_IMAGE = "ADD_RECIPE_IMAGE";
export const ADD_RECIPE_TITLE = "ADD_RECIPE_TITLE";
export const ADD_RECIPE_TYPE = "ADD_RECIPE_TYPE";
export const ADD_RECIPE_URL = "ADD_RECIPE_URL";
export const ADD_RECIPE_PHOTOS = "ADD_RECIPE_PHOTOS";
export const DELETE_RECIPE_PHOTOS = "DELETE_RECIPE_PHOTOS";
export const ADD_RECIPE_DESC = "ADD_RECIPE_DESC";
export const ADD_RECIPE_SECTION_NAME = "ADD_RECIPE_SECTION_NAME";
export const ADD_RECIPE_INGREDIENT = "ADD_RECIPE_INGREDIENT";
export const ADD_RECIPE_INSTRUCTION = "ADD_RECIPE_INSTRUCTION";
export const ADD_RECIPE_AUDIO = "ADD_RECIPE_AUDIO";
export const ADD_RECIPE_DETAIL = "ADD_RECIPE_DETAIL";

export const ADD_RECIPE_SECTION_DATA = "ADD_RECIPE_SECTION_DATA";


export const ADD_RECIPE_CATEGORY = "ADD_RECIPE_CATEGORY";

export const DO_POST_RECIPE = "DO_POST_RECIPE";
export const DO_POST_RECIPE_SUCCESS = "DO_POST_RECIPE_SUCCESS";
export const DO_POST_RECIPE_SUCCESS_WITH_INGREDIENTS = "DO_POST_RECIPE_SUCCESS_WITH_INGREDIENTS";
export const DO_POST_RECIPE_FAILED = "DO_POST_RECIPE_FAILED";

export const DO_UPDATE_RECIPE = "DO_UPDATE_RECIPE";
export const DO_UPDATE_RECIPE_SUCCESS = "DO_UPDATE_RECIPE_SUCCESS";


export const DO_POST_RECIPE_PHOTO = "DO_POST_RECIPE_PHOTO";
export const DO_POST_RECIPE_PHOTO_SUCCESS = "DO_POST_RECIPE_PHOTO_SUCCESS";
export const DO_POST_RECIPE_PHOTO_FAILED = "DO_POST_RECIPE_FAILED";

export const DO_POST_RECIPE_INGREDIENTS = "DO_POST_RECIPE_INGREDIENTS";
export const DO_POST_RECIPE_INGREDIENTS_SUCCESS = "DO_POST_RECIPE_INGREDIENTS_SUCCESS";
export const DO_POST_RECIPE_INGREDIENTS_FAILED = "DO_POST_RECIPE_INGREDIENTS_FAILED";

export const DO_POST_RECIPE_SECTION = "DO_POST_RECIPE_SECTION";
export const DO_POST_RECIPE_SECTION_SUCCESS = "DO_POST_RECIPE_SECTION_SUCCESS";
export const DO_POST_RECIPE_SECTION_FAILED = "DO_POST_RECIPE_SECTION_FAILED";

export const DO_POST_RECIPE_INSTRUCTIONS = "DO_POST_RECIPE_INSTRUCTIONS";
export const DO_POST_RECIPE_INSTRUCTIONS_SUCCESS = "DO_POST_RECIPE_INSTRUCTIONS_SUCCESS";
export const DO_POST_RECIPE_INSTRUCTIONS_FAILED = "DO_POST_RECIPE_INSTRUCTIONS_FAILED";

export const DONE_RECIPE = "DONE_RECIPE";
export const SET_RECIPE_DATA = "SET_RECIPE_DATA";

export const typesOfRecipe = {
    LINK: 0, 
    PHOTO: 1,
    RECIPE: 2,
    AUDIO: 3
}