export const DO_UPLOADIMAGE = "DO_UPLOADIMAGE";
export const DO_UPLOADIMAGE_SUCCEEDED = "DO_UPLOADIMAGE_SUCCEEDED";
export const DO_UPLOADIMAGE_FAILED = "DO_UPLOADIMAGE_FAILED";

export const DO_RESETUSERNAME = "DO_RESETUSERNAME";
export const DO_RESETUSERNAME_SUCCEEDED = "DO_RESETUSERNAME_SUCCEEDED";
export const DO_RESETUSERNAME_FAILED = "DO_RESETUSERNAME_FAILED";

export const DO_EDITPHONE = "DO_EDITPHONE";
export const DO_EDITPHONE_SUCCEEDED = "DO_EDITPHONE_SUCCEEDED";
export const DO_EDITPHONE_FAILED = "DO_EDITPHONE_FAILED";

export const DO_GETUSERSBYPHONENUMBERS = "DO_GETUSERSBYPHONENUMBERS";
export const DO_GETUSERSBYPHONENUMBERS_SUCCEEDED =
  "DO_GETUSERSBYPHONENUMBERS_SUCCEEDED";
export const DO_GETUSERSBYPHONENUMBERS_FAILED =
  "DO_GETUSERSBYPHONENUMBERS_FAILED";

export const DO_GET_CATEGORIES = "DO_GET_CATEGORIES";
export const DO_GET_CATEGORIES_SUCCEEDED = "DO_GET_CATEGORIES_SUCCEEDED";
export const DO_GET_CATEGORIES_FAILED = "DO_GET_CATEGORIES_FAILED";

export const DO_UPDATE_CATEGORIES = "DO_UPDATE_CATEGORIES";
export const DO_UPDATE_CATEGORIES_SUCCEEDED = "DO_UPDATE_CATEGORIES_SUCCEEDED";
export const DO_UPDATE_CATEGORIES_FAILED = "DO_UPDATE_CATEGORIES_FAILED";

export const DO_EDITMEASUREMENT = "DO_EDITMEASUREMENT";
export const DO_EDITMEASUREMENT_SUCCEEDED = "DO_EDITMEASUREMENT_SUCCEEDED";
export const DO_EDITMEASUREMENT_FAILED = "DO_EDITMEASUREMENT_FAILED";

export const DO_FOLLOWALL = "DO_FOLLOWALL";
export const DO_FOLLOWALL_SUCCEEDED = "DO_FOLLOWALL_SUCCEEDED";
export const DO_FOLLOWALL_FAILED = "DO_FOLLOWALL_FAILED";

export const DO_FOLLOWALLFB = "DO_FOLLOWALLFB";
export const DO_FOLLOWALLFB_SUCCEEDED = "DO_FOLLOWALLFB_SUCCEEDED";
export const DO_FOLLOWALLFB_FAILED = "DO_FOLLOWALLFB_FAILED";

export const DO_FOLLOWUSER = "DO_FOLLOWUSER";
export const DO_FOLLOWUSER_SUCCEEDED = "DO_FOLLOWUSER_SUCCEEDED";
export const DO_FOLLOWUSER_FAILED = "DO_FOLLOWUSER_FAILED";

export const DO_UNFOLLOWUSER = "DO_UNFOLLOWUSER";
export const DO_UNFOLLOWUSER_SUCCEEDED = "DO_UNFOLLOWUSER_SUCCEEDED";
export const DO_UNFOLLOWUSER_FAILED = "DO_UNFOLLOWUSER_FAILED";

export const DO_CHANGE_PROFILE_DETAILS = "DO_CHANGE_PROFILE_DETAILS";
export const DO_CHANGE_PROFILE_DETAILS_SUCCEEDED =
  "DO_CHANGE_PROFILE_DETAILS_SUCCEEDED";
export const DO_CHANGE_PROFILE_DETAILS_FAILED =
  "DO_CHANGE_PROFILE_DETAILS_FAILED";

export const DO_CHANGE_MEASURING_SYSTEM = "DO_CHANGE_MEASURING_SYSTEM";
