# Generated by Django 2.2.17 on 2020-12-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20201226_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesection',
            old_name='parent_recipe',
            new_name='recipe',
        ),
    ]
