# Generated by Django 2.2.17 on 2020-12-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20201226_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipesection',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
