# Generated by Django 2.2.17 on 2020-12-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20201226_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_ingredient', to='recipe.RecipeSection'),
        ),
        migrations.AlterField(
            model_name='recipesection',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_section', to='recipe.Recipe'),
        ),
    ]
