# Generated by Django 2.2.17 on 2021-01-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20201226_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='unit',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
