# Generated by Django 2.2.17 on 2021-01-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_recipelikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipelikes',
            options={'verbose_name': 'Recipe Likes', 'verbose_name_plural': 'Recipe Likes'},
        ),
    ]
