# Generated by Django 2.2.17 on 2021-01-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20210122_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recreated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_recreated_from', to='recipe.Recipe'),
        ),
    ]
