# Generated by Django 2.2.19 on 2021-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_images_recipeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
