# Generated by Django 2.2.19 on 2021-04-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_auto_20210311_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipeinstruction',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_instruction', to='recipe.RecipeSection'),
        ),
    ]
