# Generated by Django 2.2.19 on 2021-04-12 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_recipe_total_hours_to_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 18, 21, 10, 898767, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 18, 21, 24, 155398, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 18, 21, 32, 63824, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipeimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 18, 21, 41, 339022, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipeinstruction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 18, 21, 56, 608773, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeinstruction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipelikes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 18, 22, 0, 598523, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipelikes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipesection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 18, 22, 3, 950813, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipesection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
