# Generated by Django 2.2.24 on 2021-06-14 11:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import home.utils.upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0028_reciperatings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAITask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('created', 'Created'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('done', 'Done')], default='created', max_length=100, null=True, verbose_name='Status')),
                ('type', models.CharField(choices=[('image', 'Image'), ('website', 'Website'), ('audio', 'Audio')], max_length=100, verbose_name='Type')),
                ('scale_task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Scale Task ID')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Extra Data')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ai_task', to='recipe.Recipe', verbose_name='RecipeAITask')),
            ],
            options={
                'verbose_name': 'Recipe AI Task',
                'verbose_name_plural': 'Recipe AI Tasks',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='other_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Field'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('cup', 'Cup'), ('gallon', 'Gallon'), ('gram', 'Gram'), ('kilogram', 'Kilogram'), ('liter', 'Liter'), ('mililiter', 'Mililiter'), ('ounce', 'Ounce'), ('piece', 'Piece'), ('pinch', 'Pinch'), ('pint', 'Pint'), ('pound', 'Pound'), ('quart', 'Quart'), ('slice', 'Slice'), ('tablespoon', 'Tablespoon'), ('teaspoon', 'Teaspoon'), ('other unit', 'Other Unit')], max_length=100, null=True, verbose_name='Unit'),
        ),
        migrations.CreateModel(
            name='RecipeAIWebsiteURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('website_url', models.CharField(max_length=100, verbose_name='Website URL')),
                ('recipe_ai_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_websites', to='recipe.RecipeAITask', verbose_name='Recipe AI Task')),
            ],
            options={
                'verbose_name': 'Recipe AI Website URL',
                'verbose_name_plural': 'Recipe AI Website URLs',
            },
        ),
        migrations.CreateModel(
            name='RecipeAIImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('picture', models.ImageField(upload_to=home.utils.upload_path.get_upload_path, verbose_name='Picture')),
                ('recipe_ai_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_images', to='recipe.RecipeAITask', verbose_name='Recipe AI Task')),
            ],
            options={
                'verbose_name': 'Recipe AI Image',
                'verbose_name_plural': 'Recipe AI Images',
            },
        ),
        migrations.CreateModel(
            name='RecipeAIAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('audio_file', models.FileField(upload_to=home.utils.upload_path.get_upload_path, verbose_name='Audio File')),
                ('recipe_ai_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audio_files', to='recipe.RecipeAITask', verbose_name='Recipe AI Task')),
            ],
            options={
                'verbose_name': 'Recipe AI Audio File',
                'verbose_name_plural': 'Recipe AI Audio Files',
            },
        ),
    ]
