# Generated by Django 2.2.23 on 2021-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0030_auto_20210722_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstruction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
