# Generated by Django 2.2.17 on 2020-12-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201214_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdemographics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
