# Generated by Django 2.2.17 on 2020-12-25 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201217_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeasurement',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='usermeasurement',
            name='user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userdemographics',
            name='measurement_system',
            field=models.CharField(default='US customary system', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryName', to='users.CategoryMaster'),
        ),
        migrations.AlterField(
            model_name='userdemographics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_demo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercategory',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'following_user')},
        ),
        migrations.DeleteModel(
            name='MeasurementMaster',
        ),
        migrations.DeleteModel(
            name='UserMeasurement',
        ),
    ]
