# Generated by Django 2.2.17 on 2021-01-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210101_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
