# Generated by Django 2.2.19 on 2021-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdemographics_measuring_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdemographics',
            name='measuring_systems',
            field=models.CharField(blank=True, choices=[('metric_system', 'Metric System'), ('customary_system', 'Customary System')], default=('metric_system', 'Metric System'), max_length=50, null=True),
        ),
    ]
