# Generated by Django 2.2.19 on 2021-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210317_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdemographics',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
