# Generated by Django 2.2.23 on 2021-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userdemographics_push_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
