# Generated by Django 2.2.23 on 2021-07-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_apple_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdemographics',
            name='measurement_system',
        ),
        migrations.RemoveField(
            model_name='userdemographics',
            name='measuring_systems',
        ),
    ]
