# Generated by Django 2.2.23 on 2021-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210718_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdemographics',
            name='measurement_system',
            field=models.CharField(blank=True, choices=[('metric', 'metric'), ('customary', 'customary')], default='metric', max_length=20, null=True),
        ),
    ]
