# Generated by Django 2.2.19 on 2021-04-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category', to='recipe.Recipe'),
        ),
    ]
